# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindowGUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(QtWidgets.QWidget):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(881, 697)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.horizontalLayout.addWidget(self.label_38)
        self.displayField_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.displayField_comboBox.setObjectName("displayField_comboBox")
        self.displayField_comboBox.addItem("")
        self.displayField_comboBox.addItem("")
        self.displayField_comboBox.addItem("")
        self.horizontalLayout.addWidget(self.displayField_comboBox)
        self.gridLayout_4.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.long_GraphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.long_GraphicsView.setObjectName("long_GraphicsView")
        self.gridLayout_4.addWidget(self.long_GraphicsView, 5, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setObjectName("run_button")
        self.horizontalLayout_4.addWidget(self.run_button)
        self.simulation_progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.simulation_progressBar.setProperty("value", 24)
        self.simulation_progressBar.setObjectName("simulation_progressBar")
        self.horizontalLayout_4.addWidget(self.simulation_progressBar)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 7, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -402, 407, 889))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setEnabled(True)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.fluid_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.fluid_comboBox.setEnabled(True)
        self.fluid_comboBox.setObjectName("fluid_comboBox")
        self.fluid_comboBox.addItem("")
        self.fluid_comboBox.addItem("")
        self.fluid_comboBox.addItem("")
        self.gridLayout.addWidget(self.fluid_comboBox, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.mdot_c_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.mdot_c_lineEdit.setObjectName("mdot_c_lineEdit")
        self.gridLayout.addWidget(self.mdot_c_lineEdit, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.tubeMaterial_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.tubeMaterial_comboBox.setEnabled(True)
        self.tubeMaterial_comboBox.setObjectName("tubeMaterial_comboBox")
        self.tubeMaterial_comboBox.addItem("")
        self.tubeMaterial_comboBox.addItem("")
        self.tubeMaterial_comboBox.addItem("")
        self.tubeMaterial_comboBox.addItem("")
        self.gridLayout.addWidget(self.tubeMaterial_comboBox, 1, 1, 1, 1)
        self.mdot_h_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.mdot_h_lineEdit.setObjectName("mdot_h_lineEdit")
        self.gridLayout.addWidget(self.mdot_h_lineEdit, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.groupBox)
        self.label_40.setObjectName("label_40")
        self.gridLayout.addWidget(self.label_40, 2, 0, 1, 1)
        self.tubeThermalConductivity_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.tubeThermalConductivity_lineEdit.setObjectName("tubeThermalConductivity_lineEdit")
        self.gridLayout.addWidget(self.tubeThermalConductivity_lineEdit, 2, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.groupBox)
        self.label_41.setObjectName("label_41")
        self.gridLayout.addWidget(self.label_41, 2, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 6, 0, 1, 1)
        self.mfr_c_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.mfr_c_lineEdit.setObjectName("mfr_c_lineEdit")
        self.gridLayout.addWidget(self.mfr_c_lineEdit, 6, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.groupBox)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 6, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 7, 0, 1, 1)
        self.mfr_h_lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.mfr_h_lineEdit.setObjectName("mfr_h_lineEdit")
        self.gridLayout.addWidget(self.mfr_h_lineEdit, 7, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 7, 2, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.corrPD_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.corrPD_comboBox.setObjectName("corrPD_comboBox")
        self.corrPD_comboBox.addItem("")
        self.corrPD_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.corrPD_comboBox, 1, 1, 1, 1)
        self.e_i_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.e_i_lineEdit.setObjectName("e_i_lineEdit")
        self.gridLayout_2.addWidget(self.e_i_lineEdit, 10, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_2.addWidget(self.label_43, 4, 2, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_2.addWidget(self.label_42, 4, 0, 1, 1)
        self.Nt_col_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.Nt_col_spinBox.setMinimum(1)
        self.Nt_col_spinBox.setObjectName("Nt_col_spinBox")
        self.gridLayout_2.addWidget(self.Nt_col_spinBox, 4, 1, 1, 1)
        self.Nt_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.Nt_spinBox.setMinimum(1)
        self.Nt_spinBox.setObjectName("Nt_spinBox")
        self.gridLayout_2.addWidget(self.Nt_spinBox, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_2.addWidget(self.label_21, 10, 0, 1, 1)
        self.L_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.L_lineEdit.setObjectName("L_lineEdit")
        self.gridLayout_2.addWidget(self.L_lineEdit, 5, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 9, 2, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_2.addWidget(self.label_24, 11, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 8, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_2.addWidget(self.label_23, 10, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 5, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_2)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_2.addWidget(self.label_26, 14, 2, 1, 1)
        self.e_o_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.e_o_lineEdit.setObjectName("e_o_lineEdit")
        self.gridLayout_2.addWidget(self.e_o_lineEdit, 9, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 7, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 2, 1, 1)
        self.t_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.t_lineEdit.setObjectName("t_lineEdit")
        self.gridLayout_2.addWidget(self.t_lineEdit, 11, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 9, 0, 1, 1)
        self.s_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.s_lineEdit.setObjectName("s_lineEdit")
        self.gridLayout_2.addWidget(self.s_lineEdit, 7, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 7, 0, 1, 1)
        self.D_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.D_lineEdit.setObjectName("D_lineEdit")
        self.gridLayout_2.addWidget(self.D_lineEdit, 8, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 6, 0, 1, 1)
        self.n_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        self.n_spinBox.setMinimum(1)
        self.n_spinBox.setObjectName("n_spinBox")
        self.gridLayout_2.addWidget(self.n_spinBox, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 3, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_2.addWidget(self.label_22, 11, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 8, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_2.addWidget(self.label_46, 12, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_2.addWidget(self.label_44, 2, 0, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_2.addWidget(self.label_45, 12, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_2.addWidget(self.label_36, 1, 0, 1, 1)
        self.layout_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.layout_comboBox.setObjectName("layout_comboBox")
        self.layout_comboBox.addItem("")
        self.layout_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.layout_comboBox, 2, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_2.addWidget(self.label_25, 0, 0, 1, 1)
        self.sq_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sq_lineEdit.setObjectName("sq_lineEdit")
        self.gridLayout_2.addWidget(self.sq_lineEdit, 12, 1, 1, 1)
        self.corr_comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.corr_comboBox.setEnabled(True)
        self.corr_comboBox.setObjectName("corr_comboBox")
        self.corr_comboBox.addItem("")
        self.corr_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.corr_comboBox, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_2.addWidget(self.label_48, 13, 2, 1, 1)
        self.sl_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sl_lineEdit.setObjectName("sl_lineEdit")
        self.gridLayout_2.addWidget(self.sl_lineEdit, 13, 1, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_2.addWidget(self.label_47, 13, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setEnabled(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_3.setSpacing(5)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.Pc_in_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Pc_in_checkBox.setObjectName("Pc_in_checkBox")
        self.gridLayout_3.addWidget(self.Pc_in_checkBox, 2, 0, 1, 1)
        self.Tc_start_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.Tc_start_lineEdit.setObjectName("Tc_start_lineEdit")
        self.gridLayout_3.addWidget(self.Tc_start_lineEdit, 0, 2, 1, 1)
        self.Th_start_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.Th_start_lineEdit.setObjectName("Th_start_lineEdit")
        self.gridLayout_3.addWidget(self.Th_start_lineEdit, 1, 2, 1, 1)
        self.xc_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.xc_lineEdit.setObjectName("xc_lineEdit")
        self.gridLayout_3.addWidget(self.xc_lineEdit, 3, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setObjectName("label_34")
        self.gridLayout_3.addWidget(self.label_34, 2, 4, 1, 1)
        self.Ph_start_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.Ph_start_lineEdit.setObjectName("Ph_start_lineEdit")
        self.gridLayout_3.addWidget(self.Ph_start_lineEdit, 2, 2, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_3)
        self.label_33.setObjectName("label_33")
        self.gridLayout_3.addWidget(self.label_33, 1, 4, 1, 1)
        self.Tc_in_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Tc_in_checkBox.setObjectName("Tc_in_checkBox")
        self.gridLayout_3.addWidget(self.Tc_in_checkBox, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_3)
        self.label_32.setObjectName("label_32")
        self.gridLayout_3.addWidget(self.label_32, 0, 4, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setObjectName("label_35")
        self.gridLayout_3.addWidget(self.label_35, 3, 4, 1, 1)
        self.Tc_end_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.Tc_end_lineEdit.setObjectName("Tc_end_lineEdit")
        self.gridLayout_3.addWidget(self.Tc_end_lineEdit, 0, 3, 1, 1)
        self.Ph_end_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.Ph_end_lineEdit.setObjectName("Ph_end_lineEdit")
        self.gridLayout_3.addWidget(self.Ph_end_lineEdit, 2, 3, 1, 1)
        self.Th_end_lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.Th_end_lineEdit.setObjectName("Th_end_lineEdit")
        self.gridLayout_3.addWidget(self.Th_end_lineEdit, 1, 3, 1, 1)
        self.Th_in_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.Th_in_checkBox.setObjectName("Th_in_checkBox")
        self.gridLayout_3.addWidget(self.Th_in_checkBox, 1, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.groupBox_3)
        self.label_31.setObjectName("label_31")
        self.gridLayout_3.addWidget(self.label_31, 3, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 5, 0, 2, 1)
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 5, 10, 10)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_3.addWidget(self.label_39)
        self.configuration_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.configuration_lineEdit.setObjectName("configuration_lineEdit")
        self.verticalLayout_3.addWidget(self.configuration_lineEdit)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout_2.addWidget(self.save_button)
        self.load_button = QtWidgets.QPushButton(self.centralwidget)
        self.load_button.setObjectName("load_button")
        self.verticalLayout_2.addWidget(self.load_button)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.cut_graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.cut_graphicsView.setObjectName("cut_graphicsView")
        self.gridLayout_4.addWidget(self.cut_graphicsView, 6, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 881, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_38.setText(_translate("MainWindow", "Field to be dislayed"))
        self.displayField_comboBox.setItemText(0, _translate("MainWindow", "Water temperature"))
        self.displayField_comboBox.setItemText(1, _translate("MainWindow", "Working fluid pressure"))
        self.displayField_comboBox.setItemText(2, _translate("MainWindow", "Working fluid vapor quality"))
        self.run_button.setText(_translate("MainWindow", "Run"))
        self.groupBox.setTitle(_translate("MainWindow", "Operating Conditions"))
        self.label_5.setText(_translate("MainWindow", "[kg/m^2s]"))
        self.label_3.setText(_translate("MainWindow", "Tube material"))
        self.label_2.setText(_translate("MainWindow", "Fluid type"))
        self.fluid_comboBox.setItemText(0, _translate("MainWindow", "R134a"))
        self.fluid_comboBox.setItemText(1, _translate("MainWindow", "Ammonia"))
        self.fluid_comboBox.setItemText(2, _translate("MainWindow", "Propane"))
        self.label_7.setText(_translate("MainWindow", "[kg/m^2s]"))
        self.label_6.setText(_translate("MainWindow", "Hot fluid mass flow"))
        self.label_4.setText(_translate("MainWindow", "Working fluid mass flow "))
        self.tubeMaterial_comboBox.setItemText(0, _translate("MainWindow", "aluminium"))
        self.tubeMaterial_comboBox.setItemText(1, _translate("MainWindow", "steel"))
        self.tubeMaterial_comboBox.setItemText(2, _translate("MainWindow", "copper"))
        self.tubeMaterial_comboBox.setItemText(3, _translate("MainWindow", "custom"))
        self.label_40.setText(_translate("MainWindow", "Tube thermal conductivity"))
        self.label_41.setText(_translate("MainWindow", "[W/mK]"))
        self.label_27.setText(_translate("MainWindow", "Working fluid mass flow rate"))
        self.label_28.setText(_translate("MainWindow", "[kg/s]"))
        self.label_29.setText(_translate("MainWindow", "Hot fluid mass flow rate"))
        self.label_30.setText(_translate("MainWindow", "[kg/s]"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Geometry"))
        self.corrPD_comboBox.setItemText(0, _translate("MainWindow", "Gaddis"))
        self.corrPD_comboBox.setItemText(1, _translate("MainWindow", "Zukauskas"))
        self.label_43.setText(_translate("MainWindow", "[-]"))
        self.label_42.setText(_translate("MainWindow", "Number of tube columns"))
        self.label_21.setText(_translate("MainWindow", "Inside tube roughness"))
        self.label_20.setText(_translate("MainWindow", "[um]"))
        self.label_24.setText(_translate("MainWindow", "[m]"))
        self.label_18.setText(_translate("MainWindow", "[m]"))
        self.label_23.setText(_translate("MainWindow", "[um]"))
        self.label_12.setText(_translate("MainWindow", "[m]"))
        self.label_16.setText(_translate("MainWindow", "[m]"))
        self.label_10.setText(_translate("MainWindow", "[-]"))
        self.label_19.setText(_translate("MainWindow", "Outside tube roughness"))
        self.label_11.setText(_translate("MainWindow", "Length of tubes"))
        self.label_15.setText(_translate("MainWindow", "Tube pitch "))
        self.label_13.setText(_translate("MainWindow", "Number of cells in tube direction"))
        self.label_9.setText(_translate("MainWindow", "Number of tubes"))
        self.label_22.setText(_translate("MainWindow", "Tube thickness"))
        self.label_14.setText(_translate("MainWindow", "[-]"))
        self.label_17.setText(_translate("MainWindow", "Outer diameter"))
        self.label_46.setText(_translate("MainWindow", "[m]"))
        self.label_44.setText(_translate("MainWindow", "Layout"))
        self.label_45.setText(_translate("MainWindow", "sq"))
        self.label_36.setText(_translate("MainWindow", "Correlation pressure drop"))
        self.layout_comboBox.setItemText(0, _translate("MainWindow", "Inline"))
        self.layout_comboBox.setItemText(1, _translate("MainWindow", "Staggered"))
        self.label_25.setText(_translate("MainWindow", "Correlation heat transfer coefficient"))
        self.corr_comboBox.setItemText(0, _translate("MainWindow", "Mostinski"))
        self.corr_comboBox.setItemText(1, _translate("MainWindow", "Cooper"))
        self.label_48.setText(_translate("MainWindow", "[m]"))
        self.label_47.setText(_translate("MainWindow", "sl"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Inputs"))
        self.Pc_in_checkBox.setText(_translate("MainWindow", "Hot fluid inlet pressure"))
        self.label_34.setText(_translate("MainWindow", "[Pa]"))
        self.label_33.setText(_translate("MainWindow", "[K]"))
        self.Tc_in_checkBox.setText(_translate("MainWindow", "Working fluid inlet temperature"))
        self.label_32.setText(_translate("MainWindow", "[K]"))
        self.label_35.setText(_translate("MainWindow", "[-]"))
        self.Th_in_checkBox.setText(_translate("MainWindow", "Hot fluid inlet temperature"))
        self.label_31.setText(_translate("MainWindow", "Working fluid inlet vapor quality"))
        self.label_37.setText(_translate("MainWindow", "Boiling on tube bundles"))
        self.label_39.setText(_translate("MainWindow", "Configuration name"))
        self.save_button.setText(_translate("MainWindow", "Save configuration"))
        self.load_button.setText(_translate("MainWindow", "Load configuration"))

